### ISSUE TITLE
Issues after update to Sphinx 1.6.1

### ISSUE THREAD

**Issue by cdeil** [astropy/astropy-helpers#302] opened 2017-05-19 06:57 UTC
The Gammapy docs build broke with the update to the new Sphinx 1.6.1.
I didn't check yet for Astropy or other affiliated packages.

First I thought it's a regression in Sphinx, so I opened https://github.com/sphinx-doc/sphinx/issues/3766 yesterday. But I'm not sure if this is really a bug / regression in Sphinx, or if it's something in `astropy-helpers` that now surfaced because it relies on Sphinx internals (the traceback there mentions `AstropyBuildSphinx`).

Locally when I update to Sphinx 1.6.1 I see a different error:
```
Traceback (most recent call last):
  File "<stdin>", line 36, in <module>
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/sphinx/application.py", line 233, in __init__
    self._init_builder()
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/sphinx/application.py", line 311, in _init_builder
    self.emit('builder-inited')
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/sphinx/application.py", line 488, in emit
    return self.events.emit(event, self, *args)
  File "/Users/deil/Library/Python/3.6/lib/python/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/Users/deil/code/gammapy/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 252, in process_automodsumm_generation
    lines = automodsumm_to_autosummary_lines(sfn, app)
  File "/Users/deil/code/gammapy/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 311, in automodsumm_to_autosummary_lines
    if 'astropy_helpers.sphinx.ext.automodapi' in app._extensions:
AttributeError: 'Sphinx' object has no attribute '_extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 42, in <module>
NameError: name 'self' is not defined
Sphinx Documentation subprocess failed with return code 1
```

Looks like `astropy-helpers` accesses a private `_extensions` property in Sphinx and that now broke with Sphinx 1.6.1?

**Comment by cdeil** [comment] 2017-05-19 07:05
I see the same error in the Astropy master Sphinx build, i.e. I think any dev or CI updating to Sphinx 1.6.1 will run into this issue.

**Comment by saimn** [comment] 2017-05-19 07:32
It's a sphinx-automodapi issue: https://github.com/astropy/sphinx-automodapi/pull/22

**Comment by cdeil** [comment] 2017-05-19 07:35
@saimn - Thanks!

So what has to happen so that our CI build works again?
- merge that PR
- update astropy-helpers repo?
- update astropy-helpers in Gammapy

**Comment by saimn** [comment] 2017-05-19 07:37
I guess you are using ci-helpers ?  @bsipocz already pinned the Sphinx version there, so it may be fixed if you rebuild ?

**Comment by bsipocz** [comment] 2017-05-19 11:46
@cdeil - it shouldn't be an issue for CIs once https://github.com/astropy/ci-helpers/pull/191 is merged. Yesterday I've only included the workaround for the case when ``sphinx-gallery`` is used, but since then t became apparent that it affects ``sphinx-automodapi`` as well. That package used to be part of astropy-helpers, but separated out for v2.0.

If you and others think that it's critical enough to do a fix in astropy-helpers 1.3.x and have a quick release, I can do that, but it seems to be less hassle to stick with Sphinx 1.5.6 locally than update each and every package.
I'll send out an e-mail about it to the mailing lists, soon.

**Comment by bsipocz** [comment] 2017-05-19 14:20
@astrofrog @eteq - do you think we need to make a helpers v1.3.2 release, so this can wait to be fixed with the v2.0 release?

**Comment by bsipocz** [comment] 2017-05-29 20:12
@cdeil - At the end, I'm planning to do a 1.3.2 release to give packages a chance to be sphinx 1.6 compatible without the need to opt in astropy 2.0.

However I'm running into this issue with gammapy (that I use as a testing package). Have you seen this error before?
https://travis-ci.org/bsipocz/gammapy/jobs/237281551

Astropy seems to be working as expected with this new helpers, so now I'm not sure whether I can release or not...

**Comment by cdeil** [comment] 2017-05-29 21:13
@bsipocz - No, I haven't seen this error exactly, But it's a TypeError that looks similar to:
* https://github.com/sphinx-doc/sphinx/issues/3766
* https://github.com/astropy/astropy-helpers/issues/302
Maybe the issue isn't resolved in astropy-helpers master?

I'm offline now, but I can try to have a look tomorrow and try to reproduce / understand the issue. Let me know ...

**Comment by bsipocz** [comment] 2017-05-29 21:25
Thanks, Christoph! I had some deja-vu, and indeed now I remember seeing your sphinx issue. Anyway, this is a very weird issue, I see the same error with photutils on travis, but not on astropy core.
Also locally I can build the docs for photutils using sphinx 1.6.1 when using the 1.3.x helpers branch.

**Comment by bsipocz** [comment] 2017-05-30 11:32
Hmm, there are a bunch of new packages being picked up and installed along with sphinx 1.6.1 from conda forge. They are my current suspects, but being able to install sphinx from pip will need some hacking in ``ci-helpers`` first.

**Comment by bsipocz** [comment] 2017-05-30 17:42
Well, now it has nothing to do anymore with the sphinx version (except the dependencies it brings on board), even pip installing gwcs stopped working:
https://travis-ci.org/bsipocz/photutils/jobs/237598755

**Comment by cdeil** [comment] 2017-06-03 14:02
Based on https://github.com/sphinx-doc/sphinx/issues/3766#issuecomment-305955757 I'm closing the issue in the Sphinx tracker.

This looks like a bug in `astropy-helpers`, that changes something in a weird way, and then causes this line to fails in slightly different ways in the different build logs mentioned above:
```
File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/jinja2/utils.py", line 486, in <module>
        MutableMapping.register(LRUCache)
```
When I originally reported the issue, I remenber I looked into `jinja2/utils.py`, but that code with `MutableMapping.register(LRUCache)` hadn't been touched in years and looked OK to me. So my guess is that somehow the problem originates in `astropy-helpers` code that executes before that jinja import executes.

I'm not familiar with the `astropy-helpers` codebase or how it works, so I won't be of any help fixing this, sorry. Suggest to keep this issue open though, label it "bug" and to give it priority.

**Comment by bsipocz** [comment] 2017-06-03 14:08
This is now basically a blocker for 2.0

I played around a bit in the morning trying to reproduce the failure locally, but no success yet.

**Comment by cdeil** [comment] 2017-06-03 14:25
I also tried to follow https://github.com/sphinx-doc/sphinx/issues/3766#issuecomment-305955757 and reproduce the issue locally, but couldn't. Note that he says it only occurs if doing `import ah_bootstrap` in a fresh clone, where this occurs:
```
>>> import ah_bootstrap
Initializing astropy_helpers submodule with: `git submodule update --init -- astropy_helpers`
```
This could be a hint at where in `astropy-helpers` the issue occurs.
If you know of places where you monkey-patch things or mess with global state (e.g. in `sys`), those would be the places to look.

**Comment by bsipocz** [comment] 2017-06-03 15:13
Oh, maybe that's the issue, I tried to do it in a clean branch rather in a new clone, assuming `` git clean -dfx`` is enough.

**Closed** 2017-06-19 15:38 UTC
Labels: bug, Critical

**Comment by matteobachetti** [comment] 2017-08-11 11:56
@bsipocz I keep having this issue, and I'm not sure what next should I update/change. I'm using an updated config.py from the package template, updated astropy_helpers, etc :(

**Comment by bsipocz** [comment] 2017-08-11 12:31
can you link to the failures?

**Comment by matteobachetti** [comment] 2017-08-11 12:59
They are local failures because in the main repo I'm forcing Sphinx 1.3.1, but I can paste here the traceback:
```
Freezing version number to hendrics/version.py
running build_docs
running build
running build_py
copying hendrics/version.py -> build/lib.macosx-10.7-x86_64-3.6/hendrics
Running Sphinx v1.6.2
WARNING: while setting up extension astropy_helpers.sphinx.ext.autodoc_enhancements: directive 'autoattribute' is already registered, it will be overridden
WARNING: sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
intersphinx inventory has moved: http://docs.python.org/objects.inv -> https://docs.python.org/2/objects.inv
loading intersphinx inventory from /Users/meo/devel/spyder_projects/StingraySoftware/maltpynt_reboot/astropy_helpers/astropy_helpers/sphinx/local/python3links.inv...
loading intersphinx inventory from http://docs.scipy.org/doc/numpy/objects.inv...
intersphinx inventory has moved: http://docs.scipy.org/doc/numpy/objects.inv -> https://docs.scipy.org/doc/numpy/objects.inv
loading intersphinx inventory from http://docs.scipy.org/doc/scipy/reference/objects.inv...
intersphinx inventory has moved: http://docs.scipy.org/doc/scipy/reference/objects.inv -> https://docs.scipy.org/doc/scipy/reference/objects.inv
loading intersphinx inventory from http://matplotlib.org/objects.inv...
loading intersphinx inventory from http://docs.astropy.org/en/stable/objects.inv...
loading intersphinx inventory from http://docs.h5py.org/en/latest/objects.inv...
[autosummary] generating autosummary for: api/hendrics.test.rst, hendrics/hendrics.rst, hendrics/index.rst, hendrics/modules.rst, index.rst, install.rst, scripts/cli.rst, tutorial.rst
Traceback (most recent call last):
  File "<stdin>", line 36, in <module>
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/application.py", line 234, in __init__
    self._init_builder()
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/application.py", line 312, in _init_builder
    self.emit('builder-inited')
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/application.py", line 489, in emit
    return self.events.emit(event, self, *args)
  File "/Users/meo/anaconda/envs/py3/lib/python3.6/site-packages/Sphinx-1.6.2-py3.6.egg/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/Users/meo/devel/spyder_projects/StingraySoftware/maltpynt_reboot/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 237, in process_automodsumm_generation
    lines = automodsumm_to_autosummary_lines(sfn, app)
  File "/Users/meo/devel/spyder_projects/StingraySoftware/maltpynt_reboot/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 296, in automodsumm_to_autosummary_lines
    if 'astropy_helpers.sphinx.ext.automodapi' in app._extensions:
AttributeError: 'Sphinx' object has no attribute '_extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 42, in <module>
NameError: name 'self' is not defined

build_sphinx returning a non-zero exit code because sphinx issued documentation warnings.
Sphinx Documentation subprocess failed with return code 1

```
The code is at github.com/stingraysoftware/HENDRICS

**Comment by bsipocz** [comment] 2017-08-11 13:04
you need to update the helpers, the tracelog definitely seems to be <2.0. If you want I can add hendrics/stingray/etc to the list of packages that get the auto update PRs.

**Comment by matteobachetti** [comment] 2017-08-11 13:25
Sure, thanks! 
Strange, I ran a `git pull` from the `astropy_helpers` directory. What should I have done after that?

**Comment by bsipocz** [comment] 2017-08-11 13:31
No, that's not enough, you have to commit the changes into the main repo, too:

http://docs.astropy.org/en/latest/development/affiliated-packages.html#updating-to-the-latest-template-files

**Comment by matteobachetti** [comment] 2017-08-11 13:49
Aaaah sorry about that!

**Comment by bsipocz** [comment] 2017-08-11 13:59
No worries, indeed it's a bit confusing. If you just check out another commit in a submodule without any other modification, running setup.py of the main module will set back the submodule to its latest committed status.
