### ISSUE TITLE
build_sphinx fails under sphinx 1.3.1

### ISSUE THREAD

**Issue by stscieisenhamer** [astropy/astropy-helpers#149] opened 2015-03-19 21:55 UTC
First, using sphinx 1.2.3 under either python 2.7.9 or 3.4.3, the build_sphinx command executes fine on the straight clone of this repository.

However, using sphinx 1.3.1 under python 2.7.9, the following occurs

```
$ python setup.py build_sphinx
running build_sphinx
creating /Users/eisenham/Documents/ssbdev/astropy-affiliated-template/docs/_build
creating /Users/eisenham/Documents/ssbdev/astropy-affiliated-template/docs/_build/doctrees
creating /Users/eisenham/Documents/ssbdev/astropy-affiliated-template/docs/_build/html
creating /Users/eisenham/Documents/ssbdev/astropy-affiliated-template/docs/_static
running build
running build_py
copying packagename/./example_c.c -> build/lib.macosx-10.9-x86_64-2.7/packagename/.
running build_ext
skipping 'packagename/example_c.c' Cython extension (up-to-date)
  File "<stdin>", line 38
    print(darkred('reST markup error:'), file=sys.stderr)
                                             ^
SyntaxError: invalid syntax
Sphinx Documentation subprocess failed with return code 1
```
And, under python 3.4.3, the process gets a bit further but then....
```
$ python setup.py build_sphinx
running build_sphinx
running build
running build_py
running build_ext
Running Sphinx v1.3.1
loading pickled environment... failed: 'str' object has no attribute '__dict__'
loading intersphinx inventory from http://docs.astropy.org/en/stable/objects.inv...
loading intersphinx inventory from http://matplotlib.org/objects.inv...
loading intersphinx inventory from http://docs.h5py.org/en/latest/objects.inv...
loading intersphinx inventory from http://docs.python.org/objects.inv...
loading intersphinx inventory from http://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from /Users/eisenham/Documents/ssbdev/astropy-affiliated-template/astropy_helpers/astropy_helpers/sphinx/local/python3links.inv...
loading intersphinx inventory from http://docs.scipy.org/doc/scipy/reference/objects.inv...
[autosummary] generating autosummary for: api/packagename.do_primes.rst, api/packagename.main.rst, api/packagename.primes.rst, api/packagename.test.rst, index.rst, packagename/index.rst
Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
  File "/Users/eisenham/.virtualenvs/py3-base/lib/python3.4/site-packages/sphinx/application.py", line 188, in __init__
    self._init_builder(buildername)
  File "/Users/eisenham/.virtualenvs/py3-base/lib/python3.4/site-packages/sphinx/application.py", line 250, in _init_builder
    self.emit('builder-inited')
  File "/Users/eisenham/.virtualenvs/py3-base/lib/python3.4/site-packages/sphinx/application.py", line 497, in emit
    results.append(callback(self, *args))
  File "/Users/eisenham/Documents/ssbdev/astropy-affiliated-template/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 214, in process_automodsumm_generation
    filestosearch = [x + ext for x in env.found_docs
  File "/Users/eisenham/Documents/ssbdev/astropy-affiliated-template/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 215, in <listcomp>
    if os.path.isfile(env.doc2path(x))]\
TypeError: Can't convert 'list' object to str implicitly
Sphinx Documentation subprocess failed with return code 1
```

**Comment by embray** [comment] 2015-03-19 22:18
I'm gonna go ahead and close this as a duplicate of #148 :grin:

**Closed by embray** 2015-03-19 22:18 UTC
